"""status_updates table

Revision ID: 45c30de3c30b
Revises: 0003
Create Date: 2026-07-15 18:28:52.850814

"""
from alembic import op
import sqlalchemy as sa


revision = '45c30de3c30b'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_updates_created_at'), 'status_updates', ['created_at'], unique=False)
    op.create_index(op.f('ix_status_updates_type'), 'status_updates', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_updates_type'), table_name='status_updates')
    op.drop_index(op.f('ix_status_updates_created_at'), table_name='status_updates')
    op.drop_table('status_updates')
    # ### end Alembic commands ###
